### ISSUE TITLE
Train/Val/Test Data

### ISSUE THREAD

**Issue by ioannisa92** [idekerlab/DrugCell#1]
Could you please explain why there are cell lines and drugs repeating in train/val/test sets in your data?

I am guessing repeating drugs makes sense, but I would think that the cell lines existing in the train set should not exist in the validation and test sets.

**Comment by jisoopark** [comment]
Hi,

Who is this? And are you talking about training/test/val set in the GitHub? And do the same cell line and drug pairs have same drug response?

Jisoo Park

**Comment by jisoopark** [comment]
> Could you please explain why there are cell lines and drugs repeating in train/val/test sets in your data?
> 
> I am guessing repeating drugs makes sense, but I would think that the cell lines existing in the train set should not exist in the validation and test sets.
