### ISSUE TITLE
Output Format Not Explained

### ISSUE THREAD

**Issue by DarioS** [idekerlab/DrugCell#11]
In the README there is a good level of details about input files but nothing about output files.

**Comment by jisoopark** [comment]
Hi,

Output files are one column text file containing the predicted value of AUC for each (drug, cell line) pair in your test data set. The order of the prediction is matched with the order of (drug, cell line) pairs in your test data.

Thanks,
Jisoo

**Comment by DarioS** [comment]
To provide a useful user guide for others, this should be clearly stated in the user guide. A key purpose of a software user guide is to [provide instructions for people who didn't write the code to be able to use the software](https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/).
