### ISSUE TITLE
Installation Instructions Require Anaconda

### ISSUE THREAD

**Issue by DarioS** [idekerlab/DrugCell#13]
The H.P.C. administrator writes:

> We do not support conda on Gadi (H.P.C.) and do not recommend its usage:
> 
> - It creates many unnecessary small files slowing down file system performance.
> - Software it installs is not optimal for Gadi, compared to the natively compiled. We routinely see 30% improvements in speed.
> - Some of the packages conda installs are not compatible with Gadi and some may interfere with our modules.

Can you provide an alternative set of instructions that do not use `conda`?

**Comment by jisoopark** [comment]
Hi,

Without conda, you can skip the conda set up step and install 1) pytorch that is compatible with the version of cuda installed on your server and 2) all the packages/libraries listed in the envioronment.yml file. 

Thanks!
Jisoo
