### ISSUE TITLE
Mistakes in User Guide

### ISSUE THREAD

**Issue by DarioS** [idekerlab/DrugCell#14]
> **Example data files in _sample_ directory**
> There are three subsets of our training data provided as toy example: drugcell_train.txt, drugcell_test.txt and drugcell_val.txt

However, _sample_ directory only has three shell scripts and no data files. Acutally, I found that the small example data is in _data_ folder, unlike the instructions incorrectly state.

Also, "To run the model in a **GPU** server, execute the following: python predict_drugcell_**cpu**.py -gene2id gene2ind.txt" seems contradictory.

Lastly, where could the full input data be found, for the reader to reproduce training of the full model? It should be possible for others to reproduce the fitted model found in [Downloads](http://drugcell.ucsd.edu/downloads/) if the research is truly robust and reproducible.

**Comment by jisoopark** [comment]
Manual updated - from predict_drugcell_cpu.py -> predict_drugcell.py. drugcell_all.txt in the download folder is the full training data.
