### ISSUE TITLE
how to hash the morgen fingerprint into binary drug feature

### ISSUE THREAD

**Issue by bsun0802** [idekerlab/DrugCell#16]
Hi Author,

In the paper, the drug fingerprint is hashed into binary vector. But did not specify how. 
For my project, I have obtained the morgen fingerprint with radius = 2, and how can I hash it into binary vector?

Thanks.

**Comment by brentkuenzi** [comment]
Hi Bo, if you are using rdkit then this process is done for you already.
Just convert it into a list object

list(fingerprints)

Best,

Brent
