### ISSUE TITLE
Release of full training data

### ISSUE THREAD

**Issue by jannisborn** [idekerlab/DrugCell#20]
Hi there,

Thanks for this great work. The paper states that you extracted 509,294 drug-cell pairs from GDSC/CTRP. However, the data shared in this repository contains only 10k training samples. Essentially, this hampers the reproduction of your paper.

Would you consider releasing the entire (processed) training/validation/testing dataset? The dataset comes from public sources and since you already re-distributed parts of it, I dont see any major barriers here.
This would greatly ease reproduction and facilitate comparison with other methods. Even if one would reproduce all preprocessing steps described in the paper, two main issues would remain. First, GDSC and CTRP will have been updated since you originally downloaded the data and it might be impossible to filter out the most recent samples (especially since I do not find information on when you accessed the DBs). Secondly, it's impossible to reproduce your data split because of its randomness.

Therefore, it would be great if you could release the full processed datasets.

**Comment by jisoopark** [comment]
The entire training data is shared in: http://drugcell.ucsd.edu/downloads/drugcell_all.txt. We will update the documentation with this information.
