### ISSUE TITLE
pretrained_model avaliable?

### ISSUE THREAD

**Issue by Wootaektaek** [idekerlab/DrugCell#24]
Is this link still avaliable?

http://drugcell.ucsd.edu/downloads/

There is no reaction of the page..

or how can I get a pretrained model such as DrugCell v1.0?

**Comment by coleslaw481** [comment]
Hi,

Sorry to hear you had a problem loading the page. I just tried and the link works for me. Could you try again and re-open if you are still having problems.

thanks,

chris

**Comment by Wootaektaek** [comment]
Thanks. It was my network problem.
