### ISSUE TITLE
predict_drugcell.py with pre-trained data (https://zenodo.org/record/4011359#.X6tXjdvgpds ) failes at code/util.py:96 tokens[2]

### ISSUE THREAD

**Issue by eigoshimizu** [idekerlab/DrugCell#3]
I prepared the following files:

sample_cell2ind.txt:
0 sample_name

sample_cell2mutation.txt:
0,0,0,1, ..... ,0 (3008 data points)

sample_drugcell.txt
sample_name drug_id_1
sample_name drug_id_2
sample_name drug_id_3
...
sample_name drug_id_684

There was a description about the file contents of drug_cell.txt. I says there needs to be only two columns.

3. Test data file: drugcell_test.txt

    A tab-delimited file containing all data points that you want to estimate drug response for. The 1st column is identification of cells (genotypes) and the 2nd column is identification of drugs.

Ran the following:
python /share/pgm/tools/idekerlab-DrugCell-44daae8/code/predict_drugcell.py -gene2id /home/pgm006/work/drugcell/data/gene2ind.txt -drug2id /home/pgm006/work/drugcell/data/drug2ind.txt -cell2id /share/pgm/data/analysis/nextseq/201022_NB501923_0094_AHCYTGBGXG/results/mutation/B015-464-2020-AML-BM1/B015-464-2020-AML-BM1.genomon_mutation.result.all.combined.yokomon_out.cell2ind.txt -genotype /share/pgm/data/analysis/nextseq/201022_NB501923_0094_AHCYTGBGXG/results/mutation/B015-464-2020-AML-BM1/B015-464-2020-AML-BM1.genomon_mutation.result.all.combined.yokomon_out.cell2mutation.txt -fingerprint /home/pgm006/work/drugcell/data/drug2fingerprint.txt -hidden /share/pgm/data/analysis/nextseq/201022_NB501923_0094_AHCYTGBGXG/results/mutation/B015-464-2020-AML-BM1/B015-464-2020-AML-BM1.genomon_mutation.result.all.combined.yokomon_out_Hidden_sample -result /share/pgm/data/analysis/nextseq/201022_NB501923_0094_AHCYTGBGXG/results/mutation/B015-464-2020-AML-BM1/B015-464-2020-AML-BM1.genomon_mutation.result.all.combined.yokomon_out_Result_sample -predict /share/pgm/data/analysis/nextseq/201022_NB501923_0094_AHCYTGBGXG/results/mutation/B015-464-2020-AML-BM1/B015-464-2020-AML-BM1.genomon_mutation.result.all.combined.yokomon_out.drugcell.txt -load /share/pgm/tools/idekerlab-DrugCell-44daae8//pretrained_model/drugcell_v1.pt -cuda 0

The results says, 
File "/share/pgm/tools/idekerlab-DrugCell-44daae8/code/predict_drugcell.py", line 78, in <module>
    predict_data, cell2id_mapping, drug2id_mapping = prepare_predict_data(opt.predict, opt.cell2id, opt.drug2id)
  File "/sshare1/share/pgm/tools/idekerlab-DrugCell-44daae8/code/util.py", line 107, in prepare_predict_data
    test_feature, test_label = load_train_data(test_file, cell2id_mapping, drug2id_mapping)
  File "/sshare1/share/pgm/tools/idekerlab-DrugCell-44daae8/code/util.py", line 96, in load_train_data
    label.append([float(tokens[2])])
IndexError: list index out of range

It seems that the 3rd column in -predict parameter file.

Am I doing something wrong?
Do I have to run training?

I appreciate your help.
Thanks, Eigo.

**Comment by jisoopark** [comment]
Hi Eigo,

Even though you don't have actual drug response values for the (cell line, drug) pairs, you should have the 3rd column in the drugcell_test.txt file to be able to make a prediction. Could you add dummy values in the 3rd column in drugcell_test.txt file and re-run the prediction script for now? I will make a fix in the predict_drugcell.py file so that it can handle the 2 column file test data file in the next commit. Thanks!

Best,
Jisoo
