### ISSUE TITLE
"Repository is over its data quota" - Need alternative method to download pre-trained model. 

### ISSUE THREAD

**Issue by barabadwan** [idekerlab/DrugCell#6]
Thanks for the code but I noticed that you might be out data. Happy to help out
"This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                                                
error: failed to fetch some objects from"

**Comment by jisoopark** [comment]
Thanks for trying our model. We are now hosting the pre-trained model at:
Https://drugcell.ucsd.edu/downloads.

Could you manually download the model to use it in your analysis? I apologize for the delay that we caused while we are deciding the alternative location. Thanks so much.

Jisoo Park
