### ISSUE TITLE
Where can I get RLIPP program？

### ISSUE THREAD

**Issue by 1512474508** [idekerlab/DrugCell#7]

**Comment by jisoopark** [comment]
At this moment, we haven't published the RLIPP script as the current version is tailored to our analysis. Many parts are hard-coded and there are many moving parts that can be customized depending on the objective of users' analyses. We will work on a generalized version of the script and share it as soon as it is ready.

The RLIPP score calculation can be seen as simple as it trains linear regression models for each subsystem and the concatenation of its children. The features of the linear models can be either raw neuron values or principle components depending on where you observe a stronger signal for your analysis. While we are working on the generalized version of the RLIPP script, please feel free to modify and implement the idea. Thanks, and sorry for the inconvenience.

**Comment by 1512474508** [comment]
Good jobs！Thanks
