### ISSUE TITLE
18 GO terms do not have genes defined

### ISSUE THREAD

**Issue by ghost** [idekerlab/DrugCell#8]
Hi,

I was looking at the file [DrugCell/data/drugcell_ont.txt](https://github.com/idekerlab/DrugCell/blob/public/data/drugcell_ont.txt) and noticed that there are 18 GO terms do not have any gene defined (i.e., no row with the GO term as the first column and 'gene' as the third column).  I am curious why these GO terms do not have genes defined?  Is it because they share the same genes as their parent/child GO terms?  Any comment will be appreciated and below please find the 18 GO terms.  Thanks.

```
"GO:0002757" "GO:0002521" "GO:0002712" "GO:0008214" "GO:0007031"
"GO:0061333" "GO:0030832" "GO:0009135" "GO:0045927" "GO:0044783"
"GO:0044819" "GO:0048736" "GO:0035107" "GO:0033500" "GO:0048644"
"GO:1902403" "GO:2001233" "GO:1903825"
```

**Comment by jisoopark** [comment]
Some GO terms might NOT have directly annotated genes. They exist in the hierarchy because the number of propagated genes from their children is bigger than the number of genes annotated by their children and the difference exceeds our threshold.

**Comment by ghost** [comment]
Hi @jisoopark,

Thank you for your reply.  I appreciated it.  I am not sure if I understand the difference between `propagated genes from their children` and `genes annotated by their children`?  If possible, could you please elaborate on that?  If you could use one example GO term, that would be perfect.  Thank you.

**Comment by jisoopark** [comment]
For example, GO:0002757 has two children in our hierarchy: GO:0002429 and GO:0002758. 

121 and 102 genes are annotated by GO:0002429 and GO:0002758, respectively.

Gene propagation means that the parent, GO:0002757, will contain the union of the annotated genes of its children, GO:0002429 and GO:0002758. In this example, GO:0002757 annotates 168 genes which is union of 121 genes from GO:0002429 and 102 genes from GO:0002758. 

Note: some of 121 and 102 genes in GO:0002429 and GO:0002758 might have been propagated from their children.

Does this make sense?

**Comment by ghost** [comment]
Hi @jisoopark,

Thanks again for the explanation.  Yes, it makes perfect sense to me.  Just to confirm I understand it correctly, since GO:0002757's genes all come from its two children GO:0002429 and GO:0002758 (i.e., GO:0002757 does not have any gene other than those from its two children), therefore no gene was annotated for GO:0002757 in the `drugcell_ont.txt` file, correct?  Thanks.

**Comment by jisoopark** [comment]
Yes, that is correct. GO:0002757 has no directly annotated genes. All came from GO:0002429 and GO:0002758. You can conclude in a similar way for other 17 GO terms that you found. Thanks!

**Comment by ghost** [comment]
Thank you for your help, @jisoopark!  I appreciate it.
