### ISSUE TITLE
failed to download pretrained model at https://drugcell.ucsd.edu/downloads/

### ISSUE THREAD

**Issue by Emptyset110** [idekerlab/DrugCell#9]
although the latest update shows that the pretrained model has moved to drugcell.ucsd.edu, the link fails again I guess

**Comment by jisoopark** [comment]
Could you try http://drugcell.ucsd.edu/downloads? Not https. Thanks.

**Comment by Emptyset110** [comment]
http://drugcell.ucsd.edu/downloads works, thanks!
